# Generated by Django 3.1.1 on 2020-09-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='has_visited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='website',
            name='link',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='links_to',
            field=models.ManyToManyField(to='website.Website'),
        ),
    ]
